# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.7-node-browsers
         environment:
           RUBYOPT: "-W:no-deprecated -W:no-experimental"

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle update --bundler
            bundle install --retry=3

      - run:
          name: run tests
          command: bundle exec rake

